# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/java-connectors"
    schedule:
      interval: "weekly"
    reviewers:
      - "stheppi"
      - "davidsloan"
      - "GoMati-MU"
  #- package-ecosystem: "sbt"
  #  directory: "/"
  #  schedule:
  #    interval: "weekly"
  #  reviewers:
  #    - "stheppi"
  #    - "davidsloan"
